using System.ComponentModel;

namespace HolyBible.KJV
{
  public enum Book
  {
    Closed,
    Genesis,
    Exodus,
    Leviticus,
    Numbers,
    Deuteronomy,
    Joshua,
    Judges,
    Ruth,
    [Description("1 Samuel")] FirstSamuel,
    [Description("2 Samuel")] SecondSamuel,
    [Description("1 Kings")] FirstKings,
    [Description("2 Kings")] SecondKings,
    [Description("1 Chronicles")] FirstChronicles,
    [Description("2 Chronicles")] SecondChronicles,
    Ezra,
    Nehemiah,
    Esther,
    Job,
    Psalm,
    Proverbs,
    Ecclesiastes,
    [Description("Song of Solomon")] SongOfSolomon,
    Isaiah,
    Jeremiah,
    Lamentations,
    Ezekiel,
    Daniel,
    Hosea,
    Joel,
    Amos,
    Obadiah,
    Jonah,
    Micah,
    Nahum,
    Habakkuk,
    Zephaniah,
    Haggai,
    Zechariah,
    Malachi,
    Matthew,
    Mark,
    Luke,
    John,
    Acts,
    Romans,
    [Description("1 Corinthians")] FirstCorinthians,
    [Description("2 Corinthians")] SecondCorinthians,
    Galatians,
    Ephesians,
    Philippians,
    Colossians,
    [Description("1 Thessalonians")] FirstThessalonians,
    [Description("2 Thessalonians")] SecondThessalonians,
    [Description("1 Timothy")] FirstTimothy,
    [Description("2 Timothy")] SecondTimothy,
    Titus,
    Philemon,
    Hebrews,
    James,
    [Description("1 Peter")] FirstPeter,
    [Description("2 Peter")] SecondPeter,
    [Description("1 John")] FirstJohn,
    [Description("2 John")] SecondJohn,
    [Description("3 John")] ThirdJohn,
    Jude,
    Revelation
  }
}